<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wms.Core\Wms.Core.csproj" />
    <ProjectReference Include="..\Wms.Data\Wms.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Providers\NLogSign\" />
  </ItemGroup>

</Project>
